"""Catalog of implemented validation finding IDs. Labels describe existing checks, not legal-rate certification."""

BUILTIN_RULES = [
    ("ADV-001", "Zero Salary — Continuing Employee"),
    ("AGG-001", "Gross Pay Mismatch"),
    ("AGG-002", "Net Pay Mismatch"),
    ("AGG-003", "Zero Net Pay for Active Employee"),
    ("AGG-004", "Negative Net Pay"),
    ("ARR-001", "Arrear Period Not Stated"),
    ("ARR-002", "Arrear Period Invalid"),
    ("ARR-003", "Arrear Period Unusually Long"),
    ("ARR-004", "Arrear PF Not Due — Wage Already At Ceiling"),
    ("ATT-001", "Paid Days Differ From Attendance"),
    ("ATT-002", "LOP Differs From Attendance"),
    ("ATT-003", "No Attendance Record"),
    ("ATT-004", "Paid Days Exceed Calendar Days"),
    ("ATT-010", "Attendance Days Do Not Reconcile"),
    ("ATT-011", "Paid Days Do Not Match Loss Of Pay"),
    ("ATT-012", "Calendar Days Wrong For The Month"),
    ("ATT-013", "Impossible Attendance Value"),
    ("ATT-014", "Duplicate Attendance Rows"),
    ("ATT-015", "On Attendance But Not Paid"),
    ("ATT-020", "Pay Not Reduced For Loss Of Pay"),
    ("ATT-021", "Paid With No Paid Days"),
    ("ATT-022", "Overtime Worked But Not Paid"),
    ("ATT-023", "Overtime Paid Below The Statutory Rate"),
    ("ATT-024", "Loss Of Pay Deduction Not Verifiable"),
    ("BON-001", "Bonus Paid Above Eligibility Ceiling"),
    ("BON-002", "Statutory Bonus Outside 8.33-20% Band"),
    ("COMP-001", "Unmapped Column in Register"),
    ("COMP-002", "PF Component Missing from Register"),
    ("DATA-010", "Work State Missing for State Deduction"),
    ("DATA-011", "Bank Account Missing for Bank Payment"),
    ("DATA-012", "IFSC Missing for Bank Payment"),
    ("DATA-001", "Missing Employee ID"),
    ("DATA-003", "Negative Earning Component"),
    ("DATA-004", "All Components Are Zero"),
    ("DATA-005", "Negative Deduction"),
    ("ESI-005", "Disability ESI Coverage Missed"),
    ("ESI-006", "Employee ESI Share on Exempt Daily Wage"),
    ("GRAT-002", "Gratuity Paid Below Minimum Service"),
    ("GRAT-003", "Gratuity Deviates from Formula"),
    ("GRAT-004", "Gratuity — Service Years Unknown"),
    ("GRAT-005", "Gratuity Below Service Threshold"),
    ("ID-001", "Invalid PAN"),
    ("ID-002", "Invalid Aadhaar"),
    ("ID-003", "UAN Missing with PF Deduction"),
    ("ID-004", "ESI Number Missing with ESI Deduction"),
    ("ID-005", "Invalid IFSC"),
    ("ID-006", "Below Minimum Working Age"),
    ("ID-007", "Paid Before Date of Joining"),
    ("ID-008", "Salary After Exit Without Arrear Flag"),
    ("LOP-001", "Paid Days + LOP Days ≠ Days in Month"),
    ("LOP-003", "Paid Days Exceed Days in Month"),
    ("MOM-001", "New Joiner Detected"),
    ("MOM-004", "New Component This Month"),
    ("MOM-006", "Increment Arrear Mismatch"),
    ("MST-001", "Not in Employee Master"),
    ("MST-002", "Paid Before Joining"),
    ("MST-003", "Paid After Exit"),
    ("MST-004", "PF Deducted Without UAN"),
    ("MST-005", "ESIC Deducted Without IP Number"),
    ("MW-001", "Pay Below Configured Minimum Wage"),
    ("MW-003", "Minimum Wage Rate or Classification Missing"),
    ("PF-004", "EPS Contribution Mismatch"),
    ("PF-008", "International Worker PF Capped"),
    ("PF-009", "PF Restriction Basis Mismatch"),
    ("PT-002", "PT Exceeds Constitutional Annual Cap"),
    ("PT-003", "PT Deducted in a No-PT State"),
    ("STAT-001", "PF Employee Contribution Mismatch"),
    ("STAT-002", "PF Employer Contribution Mismatch"),
    ("STAT-004", "PF Wage is Zero"),
    ("STAT-006", "ESIC Employee Contribution Mismatch"),
    ("STAT-007", "ESIC Employer Contribution Mismatch"),
    ("STAT-008", "Professional Tax Mismatch"),
    ("STAT-009", "LWF Employee Mismatch"),
    ("STAT-010", "LWF Employer Mismatch"),
    ("STAT-014", "Gratuity Exceeds ₹20 Lakh Statutory Cap"),
    ("STRUCT-001", "Low PF Wage — Possible PF Avoidance"),
    ("STRUCT-002", "Allowance-Heavy Salary Structure"),
    ("TDS-001", "No-PAN TDS Below 20% (Sec 206AA)"),
    ("TDS-002", "Monthly TDS Deviates from Projection"),
]


def rule_family(rule_id: str) -> str:
    prefix = rule_id.split("-", 1)[0]
    if prefix in {"STAT", "PF", "ESI", "PT", "TDS", "MW", "BON", "GRAT"}:
        return "Statutory and wage"
    if prefix in {"ATT", "LOP"}:
        return "Attendance and LOP"
    if prefix in {"MST", "ID"}:
        return "Employee master and identity"
    if prefix in {"MOM", "ARR", "ADV"}:
        return "Prior period and arrears"
    return "Payroll integrity and structure"
